#define TOKEN_ONE                              1
#define TOKEN_TWO                              2
#define TOKEN_THREE                            3
#define TOKEN_FOUR                             4
#define TOKEN_FIVE                             5
#define TOKEN_SIX                              6
#define TOKEN_SEVEN                            7
#define TOKEN_EIGHT                            8
#define TOKEN_NINE                             9
#define TOKEN_ZERO                            10
#define TOKEN_TEN                             11
#define TOKEN_ELEVEN                          12
#define TOKEN_TWELVE                          13
#define TOKEN_THIRTEEN                        14
#define TOKEN_FOURTEEN                        15
#define TOKEN_FIFTEEN                         16
#define TOKEN_SIXTEEN                         17
#define TOKEN_SEVENTEEN                       18
#define TOKEN_EIGHTEEN                        19
#define TOKEN_NINETEEN                        20
#define TOKEN_TWENTY                          21
#define TOKEN_THIRTY                          22
#define TOKEN_FORTY                           23
#define TOKEN_FIFTY                           24
#define TOKEN_SIXTY                           25
#define TOKEN_SEVENTY                         26
#define TOKEN_EIGHTY                          27
#define TOKEN_NINETY                          28
#define TOKEN_HUNDRED                         29
#define TOKEN_THOUSAND                        30
#define TOKEN_MILLION                         31
#define TOKEN_BILLION                         32
#define TOKEN_TRILLION                        33
#define TOKEN_FIRST                           34
#define TOKEN_THIRD                           35
#define TOKEN_FOURTH                          36
#define TOKEN_FIFTH                           37
#define TOKEN_SIXTH                           38
#define TOKEN_SEVENTH                         39
#define TOKEN_EIGHTH                          40
#define TOKEN_NINTH                           41
#define TOKEN_HALF                            42
#define TOKEN_QUARTER                         43
