#define TOKEN_CHARACTERS                       1
#define TOKEN_AND_A                            2
#define TOKEN_QUARTER                          3
#define TOKEN_QUARTERS                         4
#define TOKEN_HALF                             5
#define TOKEN_HALVES                           6
#define TOKEN_ZERO                             7
#define TOKEN_TRILLIONTH                       8
#define TOKEN_TRILLIONTHS                      9
#define TOKEN_NUMBER                          10
#define TOKEN_TRILLION                        11
#define TOKEN_BILLIONTH                       12
#define TOKEN_BILLIONTHS                      13
#define TOKEN_BILLION                         14
#define TOKEN_MILLIONTH                       15
#define TOKEN_MILLIONTHS                      16
#define TOKEN_MILLION                         17
#define TOKEN_THOUSANDTH                      18
#define TOKEN_THOUSANDTHS                     19
#define TOKEN_THOUSAND                        20
#define TOKEN_AND                             21
#define TOKEN_HUNDREDTH                       22
#define TOKEN_HUNDREDTHS                      23
#define TOKEN_HUNDRED                         24
#define TOKEN_ONE                             25
#define TOKEN_TWO                             26
#define TOKEN_THREE                           27
#define TOKEN_FOUR                            28
#define TOKEN_FIVE                            29
#define TOKEN_SIX                             30
#define TOKEN_SEVEN                           31
#define TOKEN_EIGHT                           32
#define TOKEN_NINE                            33
#define TOKEN_TEN                             34
#define TOKEN_ELEVEN                          35
#define TOKEN_TWELVE                          36
#define TOKEN_THIRTEEN                        37
#define TOKEN_FOURTEEN                        38
#define TOKEN_FIFTEEN                         39
#define TOKEN_SIXTEEN                         40
#define TOKEN_SEVENTEEN                       41
#define TOKEN_EIGHTEEN                        42
#define TOKEN_NINETEEN                        43
#define TOKEN_TWENTY                          44
#define TOKEN_THIRTY                          45
#define TOKEN_FORTY                           46
#define TOKEN_FIFTY                           47
#define TOKEN_SIXTY                           48
#define TOKEN_SEVENTY                         49
#define TOKEN_EIGHTY                          50
#define TOKEN_NINETY                          51
#define TOKEN_FIRST                           52
#define TOKEN_FIRSTS                          53
#define TOKEN_SECOND                          54
#define TOKEN_SECONDS                         55
#define TOKEN_THIRD                           56
#define TOKEN_THIRDS                          57
#define TOKEN_FOURTH                          58
#define TOKEN_FOURTHS                         59
#define TOKEN_FIFTH                           60
#define TOKEN_FIFTHS                          61
#define TOKEN_SIXTH                           62
#define TOKEN_SIXTHS                          63
#define TOKEN_SEVENTH                         64
#define TOKEN_SEVENTHS                        65
#define TOKEN_EIGHTH                          66
#define TOKEN_EIGHTHS                         67
#define TOKEN_NINTH                           68
#define TOKEN_NINTHS                          69
#define TOKEN_TENTH                           70
#define TOKEN_TENTHS                          71
#define TOKEN_ELEVENTH                        72
#define TOKEN_ELEVENTHS                       73
#define TOKEN_TWELFTH                         74
#define TOKEN_TWELFTHS                        75
#define TOKEN_THIRTEENTH                      76
#define TOKEN_THIRTEENTHS                     77
#define TOKEN_FOURTEENTH                      78
#define TOKEN_FOURTEENTHS                     79
#define TOKEN_FIFTEENTH                       80
#define TOKEN_FIFTEENTHS                      81
#define TOKEN_SIXTEENTH                       82
#define TOKEN_SIXTEENTHS                      83
#define TOKEN_SEVENTEENTH                     84
#define TOKEN_SEVENTEENTHS                    85
#define TOKEN_EIGHTEENTH                      86
#define TOKEN_EIGHTEENTHS                     87
#define TOKEN_NINETEENTH                      88
#define TOKEN_NINETEENTHS                     89
#define TOKEN_TWENTIETH                       90
#define TOKEN_TWENTIETHS                      91
#define TOKEN_THIRTIETH                       92
#define TOKEN_THIRTIETHS                      93
#define TOKEN_FOURTIETH                       94
#define TOKEN_FOURTIETHS                      95
#define TOKEN_FIFTIETH                        96
#define TOKEN_FIFTIETHS                       97
#define TOKEN_SIXTIETH                        98
#define TOKEN_SIXTIETHS                       99
#define TOKEN_SEVENTIETH                     100
#define TOKEN_SEVENTIETHS                    101
#define TOKEN_EIGHTIETH                      102
#define TOKEN_EIGHTIETHS                     103
#define TOKEN_NINETIETH                      104
#define TOKEN_NINETIETHS                     105
