#define TOKEN_AND_A                            1
#define TOKEN_QUARTER                          2
#define TOKEN_QUARTERS                         3
#define TOKEN_HALF                             4
#define TOKEN_HALVES                           5
#define TOKEN_ZERO                             6
#define TOKEN_TRILLIONTH                       7
#define TOKEN_TRILLIONTHS                      8
#define TOKEN_NUMBER                           9
#define TOKEN_TRILLION                        10
#define TOKEN_BILLIONTH                       11
#define TOKEN_BILLIONTHS                      12
#define TOKEN_BILLION                         13
#define TOKEN_MILLIONTH                       14
#define TOKEN_MILLIONTHS                      15
#define TOKEN_MILLION                         16
#define TOKEN_THOUSANDTH                      17
#define TOKEN_THOUSANDTHS                     18
#define TOKEN_THOUSAND                        19
#define TOKEN_AND                             20
#define TOKEN_HUNDREDTH                       21
#define TOKEN_HUNDREDTHS                      22
#define TOKEN_HUNDRED                         23
#define TOKEN_ONE                             24
#define TOKEN_TWO                             25
#define TOKEN_THREE                           26
#define TOKEN_FOUR                            27
#define TOKEN_FIVE                            28
#define TOKEN_SIX                             29
#define TOKEN_SEVEN                           30
#define TOKEN_EIGHT                           31
#define TOKEN_NINE                            32
#define TOKEN_TEN                             33
#define TOKEN_ELEVEN                          34
#define TOKEN_TWELVE                          35
#define TOKEN_THIRTEEN                        36
#define TOKEN_FOURTEEN                        37
#define TOKEN_FIFTEEN                         38
#define TOKEN_SIXTEEN                         39
#define TOKEN_SEVENTEEN                       40
#define TOKEN_EIGHTEEN                        41
#define TOKEN_NINETEEN                        42
#define TOKEN_TWENTY                          43
#define TOKEN_THIRTY                          44
#define TOKEN_FORTY                           45
#define TOKEN_FIFTY                           46
#define TOKEN_SIXTY                           47
#define TOKEN_SEVENTY                         48
#define TOKEN_EIGHTY                          49
#define TOKEN_NINETY                          50
#define TOKEN_FIRST                           51
#define TOKEN_FIRSTS                          52
#define TOKEN_SECOND                          53
#define TOKEN_SECONDS                         54
#define TOKEN_THIRD                           55
#define TOKEN_THIRDS                          56
#define TOKEN_FOURTH                          57
#define TOKEN_FOURTHS                         58
#define TOKEN_FIFTH                           59
#define TOKEN_FIFTHS                          60
#define TOKEN_SIXTH                           61
#define TOKEN_SIXTHS                          62
#define TOKEN_SEVENTH                         63
#define TOKEN_SEVENTHS                        64
#define TOKEN_EIGHTH                          65
#define TOKEN_EIGHTHS                         66
#define TOKEN_NINTH                           67
#define TOKEN_NINTHS                          68
#define TOKEN_TENTH                           69
#define TOKEN_TENTHS                          70
#define TOKEN_ELEVENTH                        71
#define TOKEN_ELEVENTHS                       72
#define TOKEN_TWELFTH                         73
#define TOKEN_TWELFTHS                        74
#define TOKEN_THIRTEENTH                      75
#define TOKEN_THIRTEENTHS                     76
#define TOKEN_FOURTEENTH                      77
#define TOKEN_FOURTEENTHS                     78
#define TOKEN_FIFTEENTH                       79
#define TOKEN_FIFTEENTHS                      80
#define TOKEN_SIXTEENTH                       81
#define TOKEN_SIXTEENTHS                      82
#define TOKEN_SEVENTEENTH                     83
#define TOKEN_SEVENTEENTHS                    84
#define TOKEN_EIGHTEENTH                      85
#define TOKEN_EIGHTEENTHS                     86
#define TOKEN_NINETEENTH                      87
#define TOKEN_NINETEENTHS                     88
#define TOKEN_TWENTIETH                       89
#define TOKEN_TWENTIETHS                      90
#define TOKEN_THIRTIETH                       91
#define TOKEN_THIRTIETHS                      92
#define TOKEN_FOURTIETH                       93
#define TOKEN_FOURTIETHS                      94
#define TOKEN_FIFTIETH                        95
#define TOKEN_FIFTIETHS                       96
#define TOKEN_SIXTIETH                        97
#define TOKEN_SIXTIETHS                       98
#define TOKEN_SEVENTIETH                      99
#define TOKEN_SEVENTIETHS                    100
#define TOKEN_EIGHTIETH                      101
#define TOKEN_EIGHTIETHS                     102
#define TOKEN_NINETIETH                      103
#define TOKEN_NINETIETHS                     104
#define TOKEN_CHARACTERS                     105
