/* Generated by re2c 0.16 on Mon Nov 14 00:11:07 2016 */
#line 1 "scanner.re"
#include "scanner.def.h"
#include "parser.h"
#include "scan.h"
#include "readmem.h"

#define TOKEN_SEPARATOR 10000

int numerizer_start(scanstate *ss) {
    scanner_enter(ss);
//std:
    
#line 15 "scanner.c"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	if ((YYLIMIT - YYCURSOR) < 14) YYFILL(14);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy2;
	case '\t':
	case '\n':
	case '\f':
	case '\r':
	case ' ':
	case '-':	goto yy6;
	case '.':	goto yy9;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy12;
	case 'A':
	case 'a':	goto yy13;
	case 'B':
	case 'b':	goto yy14;
	case 'E':
	case 'e':	goto yy15;
	case 'F':
	case 'f':	goto yy16;
	case 'H':
	case 'h':	goto yy17;
	case 'M':
	case 'm':	goto yy18;
	case 'N':
	case 'n':	goto yy19;
	case 'O':
	case 'o':	goto yy20;
	case 'Q':
	case 'q':	goto yy21;
	case 'S':
	case 's':	goto yy22;
	case 'T':
	case 't':	goto yy23;
	case 'Z':
	case 'z':	goto yy24;
	default:	goto yy4;
	}
yy2:
	++YYCURSOR;
#line 153 "scanner.re"
	{ return 0; }
#line 70 "scanner.c"
yy4:
	++YYCURSOR;
yy5:
#line 155 "scanner.re"
	{ return TOKEN_CHARACTERS; }
#line 76 "scanner.c"
yy6:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\f':
	case '\r':
	case ' ':
	case '-':	goto yy6;
	default:	goto yy8;
	}
yy8:
#line 151 "scanner.re"
	{ return TOKEN_SEPARATOR; }
#line 93 "scanner.c"
yy9:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy10:
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy9;
	default:	goto yy11;
	}
yy11:
#line 22 "scanner.re"
	{ return TOKEN_NUMBER; }
#line 116 "scanner.c"
yy12:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '/':	goto yy25;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy27;
	default:	goto yy10;
	}
yy13:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case ' ':	goto yy28;
	case 'N':
	case 'n':	goto yy29;
	default:	goto yy5;
	}
yy14:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'I':
	case 'i':	goto yy30;
	default:	goto yy5;
	}
yy15:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'I':
	case 'i':	goto yy31;
	case 'L':
	case 'l':	goto yy32;
	default:	goto yy5;
	}
yy16:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'I':
	case 'i':	goto yy33;
	case 'O':
	case 'o':	goto yy34;
	default:	goto yy5;
	}
yy17:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'A':
	case 'a':	goto yy35;
	case 'U':
	case 'u':	goto yy36;
	default:	goto yy5;
	}
yy18:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'I':
	case 'i':	goto yy37;
	default:	goto yy5;
	}
yy19:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'I':
	case 'i':	goto yy38;
	default:	goto yy5;
	}
yy20:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'N':
	case 'n':	goto yy39;
	default:	goto yy5;
	}
yy21:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'U':
	case 'u':	goto yy40;
	default:	goto yy5;
	}
yy22:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'E':
	case 'e':	goto yy41;
	case 'I':
	case 'i':	goto yy42;
	default:	goto yy5;
	}
yy23:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'E':
	case 'e':	goto yy43;
	case 'H':
	case 'h':	goto yy44;
	case 'R':
	case 'r':	goto yy45;
	case 'W':
	case 'w':	goto yy46;
	default:	goto yy5;
	}
yy24:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'E':
	case 'e':	goto yy47;
	default:	goto yy5;
	}
yy25:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy48;
	default:	goto yy26;
	}
yy26:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
	case 0: 	goto yy11;
	case 1: 	goto yy5;
	case 2: 	goto yy58;
	case 3: 	goto yy77;
	case 4: 	goto yy79;
	case 5: 	goto yy105;
	case 6: 	goto yy111;
	case 7: 	goto yy50;
	case 8: 	goto yy138;
	case 9: 	goto yy160;
	case 10: 	goto yy194;
	case 11: 	goto yy238;
	case 12: 	goto yy243;
	case 13: 	goto yy248;
	case 14: 	goto yy250;
	case 15: 	goto yy264;
	case 16: 	goto yy282;
	case 17: 	goto yy290;
	case 18: 	goto yy295;
	case 19: 	goto yy303;
	case 20: 	goto yy306;
	case 21: 	goto yy308;
	default:	goto yy337;
	}
yy27:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '/':	goto yy51;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy52;
	default:	goto yy10;
	}
yy28:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'B':
	case 'b':	goto yy53;
	case 'H':
	case 'h':	goto yy54;
	case 'M':
	case 'm':	goto yy55;
	case 'T':
	case 't':	goto yy56;
	default:	goto yy26;
	}
yy29:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy57;
	default:	goto yy26;
	}
yy30:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy59;
	default:	goto yy26;
	}
yy31:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'G':
	case 'g':	goto yy60;
	default:	goto yy26;
	}
yy32:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy61;
	default:	goto yy26;
	}
yy33:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'F':
	case 'f':	goto yy62;
	case 'R':
	case 'r':	goto yy63;
	case 'V':
	case 'v':	goto yy64;
	default:	goto yy26;
	}
yy34:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy65;
	case 'U':
	case 'u':	goto yy66;
	default:	goto yy26;
	}
yy35:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy67;
	default:	goto yy26;
	}
yy36:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy68;
	default:	goto yy26;
	}
yy37:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy69;
	default:	goto yy26;
	}
yy38:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy70;
	default:	goto yy26;
	}
yy39:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy71;
	default:	goto yy26;
	}
yy40:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy73;
	default:	goto yy26;
	}
yy41:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy74;
	case 'V':
	case 'v':	goto yy75;
	default:	goto yy26;
	}
yy42:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'X':
	case 'x':	goto yy76;
	default:	goto yy26;
	}
yy43:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy78;
	default:	goto yy26;
	}
yy44:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy80;
	case 'O':
	case 'o':	goto yy81;
	case 'R':
	case 'r':	goto yy82;
	default:	goto yy26;
	}
yy45:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy83;
	default:	goto yy26;
	}
yy46:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy84;
	case 'O':
	case 'o':	goto yy85;
	default:	goto yy26;
	}
yy47:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy87;
	default:	goto yy26;
	}
yy48:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy49:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy48;
	default:	goto yy50;
	}
yy50:
#line 21 "scanner.re"
	{ return TOKEN_CHARACTERS; }
#line 485 "scanner.c"
yy51:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy88;
	default:	goto yy26;
	}
yy52:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '/':	goto yy51;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy89;
	default:	goto yy10;
	}
yy53:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy90;
	default:	goto yy26;
	}
yy54:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy91;
	default:	goto yy26;
	}
yy55:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy92;
	default:	goto yy26;
	}
yy56:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy93;
	case 'R':
	case 'r':	goto yy94;
	default:	goto yy26;
	}
yy57:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case ' ':	goto yy95;
	default:	goto yy58;
	}
yy58:
#line 24 "scanner.re"
	{ return TOKEN_AND; }
#line 558 "scanner.c"
yy59:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy96;
	default:	goto yy26;
	}
yy60:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy97;
	default:	goto yy26;
	}
yy61:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'V':
	case 'v':	goto yy98;
	default:	goto yy26;
	}
yy62:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy99;
	default:	goto yy26;
	}
yy63:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy100;
	default:	goto yy26;
	}
yy64:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy101;
	default:	goto yy26;
	}
yy65:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy103;
	default:	goto yy26;
	}
yy66:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy104;
	default:	goto yy26;
	}
yy67:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'F':
	case 'f':	goto yy106;
	default:	goto yy26;
	}
yy68:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy108;
	default:	goto yy26;
	}
yy69:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy109;
	default:	goto yy26;
	}
yy70:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy110;
	case 'T':
	case 't':	goto yy112;
	default:	goto yy26;
	}
yy71:
	++YYCURSOR;
#line 28 "scanner.re"
	{ return TOKEN_ONE; }
#line 649 "scanner.c"
yy73:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy113;
	default:	goto yy26;
	}
yy74:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy114;
	default:	goto yy26;
	}
yy75:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy115;
	default:	goto yy26;
	}
yy76:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy116;
	default:	goto yy77;
	}
yy77:
#line 33 "scanner.re"
	{ return TOKEN_SIX; }
#line 682 "scanner.c"
yy78:
	yyaccept = 4;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy117;
	default:	goto yy79;
	}
yy79:
#line 37 "scanner.re"
	{ return TOKEN_TEN; }
#line 694 "scanner.c"
yy80:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy118;
	default:	goto yy26;
	}
yy81:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy119;
	default:	goto yy26;
	}
yy82:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy120;
	default:	goto yy26;
	}
yy83:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy121;
	default:	goto yy26;
	}
yy84:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy122;
	case 'N':
	case 'n':	goto yy123;
	default:	goto yy26;
	}
yy85:
	++YYCURSOR;
#line 29 "scanner.re"
	{ return TOKEN_TWO; }
#line 736 "scanner.c"
yy87:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy124;
	default:	goto yy26;
	}
yy88:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy126;
	default:	goto yy50;
	}
yy89:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '/':	goto yy51;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy127;
	default:	goto yy10;
	}
yy90:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy129;
	default:	goto yy26;
	}
yy91:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy130;
	default:	goto yy26;
	}
yy92:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy131;
	default:	goto yy26;
	}
yy93:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy132;
	default:	goto yy26;
	}
yy94:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy133;
	default:	goto yy26;
	}
yy95:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy134;
	default:	goto yy26;
	}
yy96:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy136;
	default:	goto yy26;
	}
yy97:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy137;
	default:	goto yy26;
	}
yy98:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy139;
	default:	goto yy26;
	}
yy99:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy140;
	case 'H':
	case 'h':	goto yy141;
	case 'I':
	case 'i':	goto yy143;
	case 'Y':
	case 'y':	goto yy144;
	default:	goto yy26;
	}
yy100:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy146;
	default:	goto yy26;
	}
yy101:
	++YYCURSOR;
#line 32 "scanner.re"
	{ return TOKEN_FIVE; }
#line 863 "scanner.c"
yy103:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'Y':
	case 'y':	goto yy148;
	default:	goto yy26;
	}
yy104:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy150;
	default:	goto yy105;
	}
yy105:
#line 31 "scanner.re"
	{ return TOKEN_FOUR; }
#line 882 "scanner.c"
yy106:
	++YYCURSOR;
#line 108 "scanner.re"
	{ return TOKEN_HALF; }
#line 887 "scanner.c"
yy108:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy151;
	default:	goto yy26;
	}
yy109:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy152;
	default:	goto yy26;
	}
yy110:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy153;
	default:	goto yy111;
	}
yy111:
#line 36 "scanner.re"
	{ return TOKEN_NINE; }
#line 913 "scanner.c"
yy112:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy154;
	case 'H':
	case 'h':	goto yy155;
	default:	goto yy26;
	}
yy113:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy157;
	default:	goto yy26;
	}
yy114:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy158;
	default:	goto yy26;
	}
yy115:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy159;
	default:	goto yy26;
	}
yy116:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy161;
	case 'H':
	case 'h':	goto yy162;
	case 'I':
	case 'i':	goto yy164;
	case 'Y':
	case 'y':	goto yy165;
	default:	goto yy26;
	}
yy117:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy167;
	default:	goto yy26;
	}
yy118:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy169;
	case 'T':
	case 't':	goto yy171;
	default:	goto yy26;
	}
yy119:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy172;
	default:	goto yy26;
	}
yy120:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy173;
	default:	goto yy26;
	}
yy121:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy175;
	default:	goto yy26;
	}
yy122:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'F':
	case 'f':	goto yy176;
	case 'V':
	case 'v':	goto yy177;
	default:	goto yy26;
	}
yy123:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy178;
	default:	goto yy26;
	}
yy124:
	++YYCURSOR;
#line 27 "scanner.re"
	{ return TOKEN_ZERO; }
#line 1014 "scanner.c"
yy126:
	yyaccept = 7;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '/':	goto yy179;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy180;
	default:	goto yy50;
	}
yy127:
	yyaccept = 0;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case '.':	goto yy9;
	case '/':	goto yy25;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy127;
	default:	goto yy11;
	}
yy129:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy181;
	default:	goto yy26;
	}
yy130:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy182;
	default:	goto yy26;
	}
yy131:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy183;
	default:	goto yy26;
	}
yy132:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy184;
	default:	goto yy26;
	}
yy133:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy185;
	default:	goto yy26;
	}
yy134:
	++YYCURSOR;
#line 25 "scanner.re"
	{ return TOKEN_AND_A; }
#line 1091 "scanner.c"
yy136:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy186;
	default:	goto yy26;
	}
yy137:
	yyaccept = 8;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'E':
	case 'e':	goto yy187;
	case 'H':
	case 'h':	goto yy188;
	case 'I':
	case 'i':	goto yy190;
	case 'Y':
	case 'y':	goto yy191;
	default:	goto yy138;
	}
yy138:
#line 35 "scanner.re"
	{ return TOKEN_EIGHT; }
#line 1116 "scanner.c"
yy139:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy193;
	default:	goto yy26;
	}
yy140:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy195;
	default:	goto yy26;
	}
yy141:
	++YYCURSOR;
#line 74 "scanner.re"
	{ return TOKEN_FIFTH; }
#line 1135 "scanner.c"
yy143:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy196;
	default:	goto yy26;
	}
yy144:
	++YYCURSOR;
#line 53 "scanner.re"
	{ return TOKEN_FIFTY; }
#line 1147 "scanner.c"
yy146:
	++YYCURSOR;
#line 70 "scanner.re"
	{ return TOKEN_FIRST; }
#line 1152 "scanner.c"
yy148:
	++YYCURSOR;
#line 51 "scanner.re"
	{ return TOKEN_FORTY; }
#line 1157 "scanner.c"
yy150:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy197;
	case 'H':
	case 'h':	goto yy198;
	case 'I':
	case 'i':	goto yy200;
	case 'Y':
	case 'y':	goto yy201;
	default:	goto yy26;
	}
yy151:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy203;
	default:	goto yy26;
	}
yy152:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy204;
	default:	goto yy26;
	}
yy153:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy205;
	case 'H':
	case 'h':	goto yy206;
	case 'I':
	case 'i':	goto yy208;
	case 'Y':
	case 'y':	goto yy209;
	default:	goto yy26;
	}
yy154:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy211;
	default:	goto yy26;
	}
yy155:
	++YYCURSOR;
#line 79 "scanner.re"
	{ return TOKEN_NINTH; }
#line 1209 "scanner.c"
yy157:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy212;
	default:	goto yy26;
	}
yy158:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy213;
	default:	goto yy26;
	}
yy159:
	yyaccept = 9;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy215;
	default:	goto yy160;
	}
yy160:
#line 34 "scanner.re"
	{ return TOKEN_SEVEN; }
#line 1235 "scanner.c"
yy161:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy216;
	default:	goto yy26;
	}
yy162:
	++YYCURSOR;
#line 75 "scanner.re"
	{ return TOKEN_SIXTH; }
#line 1247 "scanner.c"
yy164:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy217;
	default:	goto yy26;
	}
yy165:
	++YYCURSOR;
#line 54 "scanner.re"
	{ return TOKEN_SIXTY; }
#line 1259 "scanner.c"
yy167:
	++YYCURSOR;
#line 81 "scanner.re"
	{ return TOKEN_TENTH; }
#line 1264 "scanner.c"
yy169:
	++YYCURSOR;
#line 72 "scanner.re"
	{ return TOKEN_THIRD; }
#line 1269 "scanner.c"
yy171:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy218;
	case 'I':
	case 'i':	goto yy219;
	case 'Y':
	case 'y':	goto yy220;
	default:	goto yy26;
	}
yy172:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy222;
	default:	goto yy26;
	}
yy173:
	++YYCURSOR;
#line 30 "scanner.re"
	{ return TOKEN_THREE; }
#line 1292 "scanner.c"
yy175:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy223;
	default:	goto yy26;
	}
yy176:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy224;
	default:	goto yy26;
	}
yy177:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy225;
	default:	goto yy26;
	}
yy178:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy227;
	case 'Y':
	case 'y':	goto yy228;
	default:	goto yy26;
	}
yy179:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy230;
	default:	goto yy26;
	}
yy180:
	yyaccept = 7;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '/':	goto yy179;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy231;
	default:	goto yy50;
	}
yy181:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy232;
	default:	goto yy26;
	}
yy182:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy233;
	default:	goto yy26;
	}
yy183:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy234;
	default:	goto yy26;
	}
yy184:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy235;
	default:	goto yy26;
	}
yy185:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy236;
	default:	goto yy26;
	}
yy186:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy237;
	default:	goto yy26;
	}
yy187:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy239;
	default:	goto yy26;
	}
yy188:
	++YYCURSOR;
#line 77 "scanner.re"
	{ return TOKEN_EIGHTH; }
#line 1408 "scanner.c"
yy190:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy240;
	default:	goto yy26;
	}
yy191:
	++YYCURSOR;
#line 56 "scanner.re"
	{ return TOKEN_EIGHTY; }
#line 1420 "scanner.c"
yy193:
	yyaccept = 10;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy241;
	default:	goto yy194;
	}
yy194:
#line 38 "scanner.re"
	{ return TOKEN_ELEVEN; }
#line 1432 "scanner.c"
yy195:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy242;
	default:	goto yy26;
	}
yy196:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy244;
	default:	goto yy26;
	}
yy197:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy245;
	default:	goto yy26;
	}
yy198:
	++YYCURSOR;
#line 73 "scanner.re"
	{ return TOKEN_FOURTH; }
#line 1458 "scanner.c"
yy200:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy246;
	default:	goto yy26;
	}
yy201:
	++YYCURSOR;
#line 52 "scanner.re"
	{ return TOKEN_FORTY; }
#line 1470 "scanner.c"
yy203:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy247;
	default:	goto yy26;
	}
yy204:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy249;
	default:	goto yy26;
	}
yy205:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy251;
	default:	goto yy26;
	}
yy206:
	++YYCURSOR;
#line 78 "scanner.re"
	{ return TOKEN_NINTH; }
#line 1496 "scanner.c"
yy208:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy252;
	default:	goto yy26;
	}
yy209:
	++YYCURSOR;
#line 57 "scanner.re"
	{ return TOKEN_NINETY; }
#line 1508 "scanner.c"
yy211:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy253;
	default:	goto yy26;
	}
yy212:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy255;
	default:	goto yy26;
	}
yy213:
	++YYCURSOR;
#line 71 "scanner.re"
	{ return TOKEN_SECOND; }
#line 1527 "scanner.c"
yy215:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy257;
	case 'H':
	case 'h':	goto yy258;
	case 'I':
	case 'i':	goto yy260;
	case 'Y':
	case 'y':	goto yy261;
	default:	goto yy26;
	}
yy216:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy263;
	default:	goto yy26;
	}
yy217:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy265;
	default:	goto yy26;
	}
yy218:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy266;
	default:	goto yy26;
	}
yy219:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy267;
	default:	goto yy26;
	}
yy220:
	++YYCURSOR;
#line 50 "scanner.re"
	{ return TOKEN_THIRTY; }
#line 1573 "scanner.c"
yy222:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy268;
	default:	goto yy26;
	}
yy223:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy269;
	default:	goto yy26;
	}
yy224:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy270;
	default:	goto yy26;
	}
yy225:
	++YYCURSOR;
#line 39 "scanner.re"
	{ return TOKEN_TWELVE; }
#line 1599 "scanner.c"
yy227:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy272;
	default:	goto yy26;
	}
yy228:
	++YYCURSOR;
#line 49 "scanner.re"
	{ return TOKEN_TWENTY; }
#line 1611 "scanner.c"
yy230:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy273;
	default:	goto yy26;
	}
yy231:
	yyaccept = 7;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '/':	goto yy179;
	default:	goto yy49;
	}
yy232:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy275;
	default:	goto yy26;
	}
yy233:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy276;
	default:	goto yy26;
	}
yy234:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy277;
	default:	goto yy26;
	}
yy235:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy278;
	default:	goto yy26;
	}
yy236:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy279;
	default:	goto yy26;
	}
yy237:
	yyaccept = 11;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy280;
	default:	goto yy238;
	}
yy238:
#line 66 "scanner.re"
	{ return TOKEN_BILLION; }
#line 1680 "scanner.c"
yy239:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy281;
	default:	goto yy26;
	}
yy240:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy283;
	default:	goto yy26;
	}
yy241:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy284;
	default:	goto yy26;
	}
yy242:
	yyaccept = 12;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy286;
	default:	goto yy243;
	}
yy243:
#line 42 "scanner.re"
	{ return TOKEN_FIFTEEN; }
#line 1713 "scanner.c"
yy244:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy287;
	default:	goto yy26;
	}
yy245:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy289;
	default:	goto yy26;
	}
yy246:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy291;
	default:	goto yy26;
	}
yy247:
	yyaccept = 13;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy292;
	default:	goto yy248;
	}
yy248:
#line 60 "scanner.re"
	{ return TOKEN_HUNDRED; }
#line 1746 "scanner.c"
yy249:
	yyaccept = 14;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy293;
	default:	goto yy250;
	}
yy250:
#line 64 "scanner.re"
	{ return TOKEN_MILLION; }
#line 1758 "scanner.c"
yy251:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy294;
	default:	goto yy26;
	}
yy252:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy296;
	default:	goto yy26;
	}
yy253:
	++YYCURSOR;
#line 47 "scanner.re"
	{ return TOKEN_NINETEEN; }
#line 1777 "scanner.c"
yy255:
	++YYCURSOR;
#line 107 "scanner.re"
	{ return TOKEN_QUARTER; }
#line 1782 "scanner.c"
yy257:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy297;
	default:	goto yy26;
	}
yy258:
	++YYCURSOR;
#line 76 "scanner.re"
	{ return TOKEN_SEVENTH; }
#line 1794 "scanner.c"
yy260:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy298;
	default:	goto yy26;
	}
yy261:
	++YYCURSOR;
#line 55 "scanner.re"
	{ return TOKEN_SEVENTY; }
#line 1806 "scanner.c"
yy263:
	yyaccept = 15;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy299;
	default:	goto yy264;
	}
yy264:
#line 43 "scanner.re"
	{ return TOKEN_SIXTEEN; }
#line 1818 "scanner.c"
yy265:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy300;
	default:	goto yy26;
	}
yy266:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy302;
	default:	goto yy26;
	}
yy267:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy304;
	default:	goto yy26;
	}
yy268:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy305;
	default:	goto yy26;
	}
yy269:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy307;
	default:	goto yy26;
	}
yy270:
	++YYCURSOR;
#line 83 "scanner.re"
	{ return TOKEN_TWELFTH; }
#line 1858 "scanner.c"
yy272:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy309;
	default:	goto yy26;
	}
yy273:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy310;
	default:	goto yy274;
	}
yy274:
#line 20 "scanner.re"
	{ return TOKEN_CHARACTERS; }
#line 1884 "scanner.c"
yy275:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy311;
	default:	goto yy26;
	}
yy276:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy313;
	default:	goto yy26;
	}
yy277:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy315;
	default:	goto yy26;
	}
yy278:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy317;
	default:	goto yy26;
	}
yy279:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy318;
	default:	goto yy26;
	}
yy280:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy319;
	default:	goto yy26;
	}
yy281:
	yyaccept = 16;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy321;
	default:	goto yy282;
	}
yy282:
#line 45 "scanner.re"
	{ return TOKEN_EIGHTEEN; }
#line 1938 "scanner.c"
yy283:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy322;
	default:	goto yy26;
	}
yy284:
	++YYCURSOR;
#line 82 "scanner.re"
	{ return TOKEN_ELEVENTH; }
#line 1950 "scanner.c"
yy286:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy324;
	default:	goto yy26;
	}
yy287:
	++YYCURSOR;
#line 95 "scanner.re"
	{ return TOKEN_FIFTIETH; }
#line 1962 "scanner.c"
yy289:
	yyaccept = 17;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy326;
	default:	goto yy290;
	}
yy290:
#line 41 "scanner.re"
	{ return TOKEN_FOURTEEN; }
#line 1974 "scanner.c"
yy291:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy327;
	default:	goto yy26;
	}
yy292:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy329;
	default:	goto yy26;
	}
yy293:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy331;
	default:	goto yy26;
	}
yy294:
	yyaccept = 18;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy333;
	default:	goto yy295;
	}
yy295:
#line 46 "scanner.re"
	{ return TOKEN_NINETEEN; }
#line 2007 "scanner.c"
yy296:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy334;
	default:	goto yy26;
	}
yy297:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy336;
	default:	goto yy26;
	}
yy298:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy338;
	default:	goto yy26;
	}
yy299:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy339;
	default:	goto yy26;
	}
yy300:
	++YYCURSOR;
#line 96 "scanner.re"
	{ return TOKEN_SIXTIETH; }
#line 2040 "scanner.c"
yy302:
	yyaccept = 19;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy341;
	default:	goto yy303;
	}
yy303:
#line 40 "scanner.re"
	{ return TOKEN_THIRTEEN; }
#line 2052 "scanner.c"
yy304:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy342;
	default:	goto yy26;
	}
yy305:
	yyaccept = 20;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy344;
	default:	goto yy306;
	}
yy306:
#line 62 "scanner.re"
	{ return TOKEN_THOUSAND; }
#line 2071 "scanner.c"
yy307:
	yyaccept = 21;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy345;
	default:	goto yy308;
	}
yy308:
#line 68 "scanner.re"
	{ return TOKEN_TRILLION; }
#line 2083 "scanner.c"
yy309:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy346;
	default:	goto yy26;
	}
yy310:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy348;
	default:	goto yy274;
	}
yy311:
	++YYCURSOR;
#line 65 "scanner.re"
	{ return TOKEN_BILLION; }
#line 2110 "scanner.c"
yy313:
	++YYCURSOR;
#line 59 "scanner.re"
	{ return TOKEN_HUNDRED; }
#line 2115 "scanner.c"
yy315:
	++YYCURSOR;
#line 63 "scanner.re"
	{ return TOKEN_MILLION; }
#line 2120 "scanner.c"
yy317:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy349;
	default:	goto yy26;
	}
yy318:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy351;
	default:	goto yy26;
	}
yy319:
	++YYCURSOR;
#line 104 "scanner.re"
	{ return TOKEN_BILLIONTH; }
#line 2139 "scanner.c"
yy321:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy353;
	default:	goto yy26;
	}
yy322:
	++YYCURSOR;
#line 98 "scanner.re"
	{ return TOKEN_EIGHTIETH; }
#line 2151 "scanner.c"
yy324:
	++YYCURSOR;
#line 86 "scanner.re"
	{ return TOKEN_FIFTEENTH; }
#line 2156 "scanner.c"
yy326:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy355;
	default:	goto yy26;
	}
yy327:
	++YYCURSOR;
#line 94 "scanner.re"
	{ return TOKEN_FOURTIETH; }
#line 2168 "scanner.c"
yy329:
	++YYCURSOR;
#line 101 "scanner.re"
	{ return TOKEN_HUNDREDTH; }
#line 2173 "scanner.c"
yy331:
	++YYCURSOR;
#line 103 "scanner.re"
	{ return TOKEN_MILLIONTH; }
#line 2178 "scanner.c"
yy333:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy357;
	default:	goto yy26;
	}
yy334:
	++YYCURSOR;
#line 99 "scanner.re"
	{ return TOKEN_NINETIETH; }
#line 2190 "scanner.c"
yy336:
	yyaccept = 22;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy359;
	default:	goto yy337;
	}
yy337:
#line 44 "scanner.re"
	{ return TOKEN_SEVENTEEN; }
#line 2202 "scanner.c"
yy338:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy360;
	default:	goto yy26;
	}
yy339:
	++YYCURSOR;
#line 87 "scanner.re"
	{ return TOKEN_SIXTEENTH; }
#line 2214 "scanner.c"
yy341:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy362;
	default:	goto yy26;
	}
yy342:
	++YYCURSOR;
#line 93 "scanner.re"
	{ return TOKEN_THIRTIETH; }
#line 2226 "scanner.c"
yy344:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy364;
	default:	goto yy26;
	}
yy345:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy366;
	default:	goto yy26;
	}
yy346:
	++YYCURSOR;
#line 92 "scanner.re"
	{ return TOKEN_TWENTIETH; }
#line 2245 "scanner.c"
yy348:
	yych = *++YYCURSOR;
	goto yy274;
yy349:
	++YYCURSOR;
#line 61 "scanner.re"
	{ return TOKEN_THOUSAND; }
#line 2253 "scanner.c"
yy351:
	++YYCURSOR;
#line 67 "scanner.re"
	{ return TOKEN_TRILLION; }
#line 2258 "scanner.c"
yy353:
	++YYCURSOR;
#line 89 "scanner.re"
	{ return TOKEN_EIGHTEENTH; }
#line 2263 "scanner.c"
yy355:
	++YYCURSOR;
#line 85 "scanner.re"
	{ return TOKEN_FOURTEENTH; }
#line 2268 "scanner.c"
yy357:
	++YYCURSOR;
#line 90 "scanner.re"
	{ return TOKEN_NINETEENTH; }
#line 2273 "scanner.c"
yy359:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy368;
	default:	goto yy26;
	}
yy360:
	++YYCURSOR;
#line 97 "scanner.re"
	{ return TOKEN_SEVENTIETH; }
#line 2285 "scanner.c"
yy362:
	++YYCURSOR;
#line 84 "scanner.re"
	{ return TOKEN_THIRTEENTH; }
#line 2290 "scanner.c"
yy364:
	++YYCURSOR;
#line 102 "scanner.re"
	{ return TOKEN_THOUSANDTH; }
#line 2295 "scanner.c"
yy366:
	++YYCURSOR;
#line 105 "scanner.re"
	{ return TOKEN_TRILLIONTH; }
#line 2300 "scanner.c"
yy368:
	++YYCURSOR;
#line 88 "scanner.re"
	{ return TOKEN_SEVENTEENTH; }
#line 2305 "scanner.c"
}
#line 156 "scanner.re"

}

/*
scanstate* numerizer_attach(scanstate *ss)
{
	if(ss) {
		ss->state = numerizer_start;
		ss->line = 1;
	}

	return ss;
}
*/
