/* Generated by re2c 0.16 on Sat Nov 12 19:07:23 2016 */
#line 1 "scanner.re"
#include "scanner.def.h"
#include "parser.h"
#include "scan.h"
#include "readmem.h"

#define TOKEN_SEPARATOR 10000

int numerizer_start(scanstate *ss) {
    scanner_enter(ss);
//std:
    
#line 15 "scanner.c"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	if ((YYLIMIT - YYCURSOR) < 11) YYFILL(11);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy2;
	case '\t':
	case '\n':
	case '\f':
	case '\r':
	case ' ':
	case '-':	goto yy6;
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy9;
	case 'A':
	case 'a':	goto yy12;
	case 'B':
	case 'b':	goto yy13;
	case 'E':
	case 'e':	goto yy14;
	case 'F':
	case 'f':	goto yy15;
	case 'H':
	case 'h':	goto yy16;
	case 'M':
	case 'm':	goto yy17;
	case 'N':
	case 'n':	goto yy18;
	case 'O':
	case 'o':	goto yy19;
	case 'Q':
	case 'q':	goto yy20;
	case 'S':
	case 's':	goto yy21;
	case 'T':
	case 't':	goto yy22;
	case 'Z':
	case 'z':	goto yy23;
	default:	goto yy4;
	}
yy2:
	++YYCURSOR;
#line 144 "scanner.re"
	{ return 0; }
#line 70 "scanner.c"
yy4:
	++YYCURSOR;
yy5:
#line 146 "scanner.re"
	{ return TOKEN_CHARACTERS; }
#line 76 "scanner.c"
yy6:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\f':
	case '\r':
	case ' ':
	case '-':	goto yy6;
	default:	goto yy8;
	}
yy8:
#line 142 "scanner.re"
	{ return TOKEN_SEPARATOR; }
#line 93 "scanner.c"
yy9:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy9;
	default:	goto yy11;
	}
yy11:
#line 18 "scanner.re"
	{ return TOKEN_NUMBER; }
#line 115 "scanner.c"
yy12:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'N':
	case 'n':	goto yy24;
	default:	goto yy5;
	}
yy13:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'I':
	case 'i':	goto yy26;
	default:	goto yy5;
	}
yy14:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'I':
	case 'i':	goto yy27;
	case 'L':
	case 'l':	goto yy28;
	default:	goto yy5;
	}
yy15:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'I':
	case 'i':	goto yy29;
	case 'O':
	case 'o':	goto yy30;
	default:	goto yy5;
	}
yy16:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'A':
	case 'a':	goto yy31;
	case 'U':
	case 'u':	goto yy32;
	default:	goto yy5;
	}
yy17:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'I':
	case 'i':	goto yy33;
	default:	goto yy5;
	}
yy18:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'I':
	case 'i':	goto yy34;
	default:	goto yy5;
	}
yy19:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'N':
	case 'n':	goto yy35;
	default:	goto yy5;
	}
yy20:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'U':
	case 'u':	goto yy36;
	default:	goto yy5;
	}
yy21:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'E':
	case 'e':	goto yy37;
	case 'I':
	case 'i':	goto yy38;
	default:	goto yy5;
	}
yy22:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'E':
	case 'e':	goto yy39;
	case 'H':
	case 'h':	goto yy40;
	case 'R':
	case 'r':	goto yy41;
	case 'W':
	case 'w':	goto yy42;
	default:	goto yy5;
	}
yy23:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'E':
	case 'e':	goto yy43;
	default:	goto yy5;
	}
yy24:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy44;
	default:	goto yy25;
	}
yy25:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
	case 0: 	goto yy5;
	case 1: 	goto yy45;
	case 2: 	goto yy64;
	case 3: 	goto yy66;
	case 4: 	goto yy85;
	case 5: 	goto yy91;
	case 6: 	goto yy110;
	case 7: 	goto yy132;
	case 8: 	goto yy159;
	case 9: 	goto yy196;
	case 10: 	goto yy201;
	case 11: 	goto yy206;
	case 12: 	goto yy208;
	case 13: 	goto yy222;
	case 14: 	goto yy233;
	case 15: 	goto yy241;
	case 16: 	goto yy246;
	case 17: 	goto yy254;
	case 18: 	goto yy257;
	case 19: 	goto yy259;
	default:	goto yy279;
	}
yy26:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy46;
	default:	goto yy25;
	}
yy27:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'G':
	case 'g':	goto yy47;
	default:	goto yy25;
	}
yy28:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy48;
	default:	goto yy25;
	}
yy29:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'F':
	case 'f':	goto yy49;
	case 'R':
	case 'r':	goto yy50;
	case 'V':
	case 'v':	goto yy51;
	default:	goto yy25;
	}
yy30:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy52;
	case 'U':
	case 'u':	goto yy53;
	default:	goto yy25;
	}
yy31:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy54;
	default:	goto yy25;
	}
yy32:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy55;
	default:	goto yy25;
	}
yy33:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy56;
	default:	goto yy25;
	}
yy34:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy57;
	default:	goto yy25;
	}
yy35:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy58;
	default:	goto yy25;
	}
yy36:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy60;
	default:	goto yy25;
	}
yy37:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy61;
	case 'V':
	case 'v':	goto yy62;
	default:	goto yy25;
	}
yy38:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'X':
	case 'x':	goto yy63;
	default:	goto yy25;
	}
yy39:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy65;
	default:	goto yy25;
	}
yy40:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy67;
	case 'O':
	case 'o':	goto yy68;
	case 'R':
	case 'r':	goto yy69;
	default:	goto yy25;
	}
yy41:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy70;
	default:	goto yy25;
	}
yy42:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy71;
	case 'O':
	case 'o':	goto yy72;
	default:	goto yy25;
	}
yy43:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy74;
	default:	goto yy25;
	}
yy44:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case ' ':	goto yy75;
	default:	goto yy45;
	}
yy45:
#line 20 "scanner.re"
	{ return TOKEN_AND; }
#line 408 "scanner.c"
yy46:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy76;
	default:	goto yy25;
	}
yy47:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy77;
	default:	goto yy25;
	}
yy48:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'V':
	case 'v':	goto yy78;
	default:	goto yy25;
	}
yy49:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy79;
	default:	goto yy25;
	}
yy50:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy80;
	default:	goto yy25;
	}
yy51:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy81;
	default:	goto yy25;
	}
yy52:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy83;
	default:	goto yy25;
	}
yy53:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy84;
	default:	goto yy25;
	}
yy54:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'F':
	case 'f':	goto yy86;
	default:	goto yy25;
	}
yy55:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy88;
	default:	goto yy25;
	}
yy56:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy89;
	default:	goto yy25;
	}
yy57:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy90;
	case 'T':
	case 't':	goto yy92;
	default:	goto yy25;
	}
yy58:
	++YYCURSOR;
#line 24 "scanner.re"
	{ return TOKEN_ONE; }
#line 499 "scanner.c"
yy60:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy93;
	default:	goto yy25;
	}
yy61:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy94;
	default:	goto yy25;
	}
yy62:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy95;
	default:	goto yy25;
	}
yy63:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy96;
	default:	goto yy64;
	}
yy64:
#line 29 "scanner.re"
	{ return TOKEN_SIX; }
#line 532 "scanner.c"
yy65:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy97;
	default:	goto yy66;
	}
yy66:
#line 33 "scanner.re"
	{ return TOKEN_TEN; }
#line 544 "scanner.c"
yy67:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy98;
	default:	goto yy25;
	}
yy68:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy99;
	default:	goto yy25;
	}
yy69:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy100;
	default:	goto yy25;
	}
yy70:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy101;
	default:	goto yy25;
	}
yy71:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy102;
	case 'N':
	case 'n':	goto yy103;
	default:	goto yy25;
	}
yy72:
	++YYCURSOR;
#line 25 "scanner.re"
	{ return TOKEN_TWO; }
#line 586 "scanner.c"
yy74:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy104;
	default:	goto yy25;
	}
yy75:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy106;
	default:	goto yy25;
	}
yy76:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy108;
	default:	goto yy25;
	}
yy77:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy109;
	default:	goto yy25;
	}
yy78:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy111;
	default:	goto yy25;
	}
yy79:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy112;
	case 'H':
	case 'h':	goto yy113;
	case 'I':
	case 'i':	goto yy115;
	case 'Y':
	case 'y':	goto yy116;
	default:	goto yy25;
	}
yy80:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy118;
	default:	goto yy25;
	}
yy81:
	++YYCURSOR;
#line 28 "scanner.re"
	{ return TOKEN_FIVE; }
#line 646 "scanner.c"
yy83:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'Y':
	case 'y':	goto yy120;
	default:	goto yy25;
	}
yy84:
	yyaccept = 4;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy122;
	default:	goto yy85;
	}
yy85:
#line 27 "scanner.re"
	{ return TOKEN_FOUR; }
#line 665 "scanner.c"
yy86:
	++YYCURSOR;
#line 99 "scanner.re"
	{ return TOKEN_HALF; }
#line 670 "scanner.c"
yy88:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy123;
	default:	goto yy25;
	}
yy89:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy124;
	default:	goto yy25;
	}
yy90:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy125;
	default:	goto yy91;
	}
yy91:
#line 32 "scanner.re"
	{ return TOKEN_NINE; }
#line 696 "scanner.c"
yy92:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy126;
	case 'H':
	case 'h':	goto yy127;
	default:	goto yy25;
	}
yy93:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy129;
	default:	goto yy25;
	}
yy94:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy130;
	default:	goto yy25;
	}
yy95:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy131;
	default:	goto yy25;
	}
yy96:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy133;
	case 'H':
	case 'h':	goto yy134;
	case 'I':
	case 'i':	goto yy136;
	case 'Y':
	case 'y':	goto yy137;
	default:	goto yy25;
	}
yy97:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy139;
	default:	goto yy25;
	}
yy98:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy141;
	case 'T':
	case 't':	goto yy143;
	default:	goto yy25;
	}
yy99:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy144;
	default:	goto yy25;
	}
yy100:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy145;
	default:	goto yy25;
	}
yy101:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy147;
	default:	goto yy25;
	}
yy102:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'F':
	case 'f':	goto yy148;
	case 'V':
	case 'v':	goto yy149;
	default:	goto yy25;
	}
yy103:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy150;
	default:	goto yy25;
	}
yy104:
	++YYCURSOR;
#line 23 "scanner.re"
	{ return TOKEN_ZERO; }
#line 797 "scanner.c"
yy106:
	++YYCURSOR;
#line 21 "scanner.re"
	{ return TOKEN_AND_A; }
#line 802 "scanner.c"
yy108:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy151;
	default:	goto yy25;
	}
yy109:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'E':
	case 'e':	goto yy152;
	case 'H':
	case 'h':	goto yy153;
	case 'I':
	case 'i':	goto yy155;
	case 'Y':
	case 'y':	goto yy156;
	default:	goto yy110;
	}
yy110:
#line 31 "scanner.re"
	{ return TOKEN_EIGHT; }
#line 827 "scanner.c"
yy111:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy158;
	default:	goto yy25;
	}
yy112:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy160;
	default:	goto yy25;
	}
yy113:
	++YYCURSOR;
#line 65 "scanner.re"
	{ return TOKEN_FIFTH; }
#line 846 "scanner.c"
yy115:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy161;
	default:	goto yy25;
	}
yy116:
	++YYCURSOR;
#line 49 "scanner.re"
	{ return TOKEN_FIFTY; }
#line 858 "scanner.c"
yy118:
	++YYCURSOR;
#line 61 "scanner.re"
	{ return TOKEN_FIRST; }
#line 863 "scanner.c"
yy120:
	++YYCURSOR;
#line 47 "scanner.re"
	{ return TOKEN_FORTY; }
#line 868 "scanner.c"
yy122:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy162;
	case 'H':
	case 'h':	goto yy163;
	case 'I':
	case 'i':	goto yy165;
	case 'Y':
	case 'y':	goto yy166;
	default:	goto yy25;
	}
yy123:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy168;
	default:	goto yy25;
	}
yy124:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy169;
	default:	goto yy25;
	}
yy125:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy170;
	case 'H':
	case 'h':	goto yy171;
	case 'I':
	case 'i':	goto yy173;
	case 'Y':
	case 'y':	goto yy174;
	default:	goto yy25;
	}
yy126:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy176;
	default:	goto yy25;
	}
yy127:
	++YYCURSOR;
#line 70 "scanner.re"
	{ return TOKEN_NINTH; }
#line 920 "scanner.c"
yy129:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy177;
	default:	goto yy25;
	}
yy130:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy178;
	default:	goto yy25;
	}
yy131:
	yyaccept = 7;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy180;
	default:	goto yy132;
	}
yy132:
#line 30 "scanner.re"
	{ return TOKEN_SEVEN; }
#line 946 "scanner.c"
yy133:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy181;
	default:	goto yy25;
	}
yy134:
	++YYCURSOR;
#line 66 "scanner.re"
	{ return TOKEN_SIXTH; }
#line 958 "scanner.c"
yy136:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy182;
	default:	goto yy25;
	}
yy137:
	++YYCURSOR;
#line 50 "scanner.re"
	{ return TOKEN_SIXTY; }
#line 970 "scanner.c"
yy139:
	++YYCURSOR;
#line 72 "scanner.re"
	{ return TOKEN_TENTH; }
#line 975 "scanner.c"
yy141:
	++YYCURSOR;
#line 63 "scanner.re"
	{ return TOKEN_THIRD; }
#line 980 "scanner.c"
yy143:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy183;
	case 'I':
	case 'i':	goto yy184;
	case 'Y':
	case 'y':	goto yy185;
	default:	goto yy25;
	}
yy144:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy187;
	default:	goto yy25;
	}
yy145:
	++YYCURSOR;
#line 26 "scanner.re"
	{ return TOKEN_THREE; }
#line 1003 "scanner.c"
yy147:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy188;
	default:	goto yy25;
	}
yy148:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy189;
	default:	goto yy25;
	}
yy149:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy190;
	default:	goto yy25;
	}
yy150:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy192;
	case 'Y':
	case 'y':	goto yy193;
	default:	goto yy25;
	}
yy151:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy195;
	default:	goto yy25;
	}
yy152:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy197;
	default:	goto yy25;
	}
yy153:
	++YYCURSOR;
#line 68 "scanner.re"
	{ return TOKEN_EIGHTH; }
#line 1052 "scanner.c"
yy155:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy198;
	default:	goto yy25;
	}
yy156:
	++YYCURSOR;
#line 52 "scanner.re"
	{ return TOKEN_EIGHTY; }
#line 1064 "scanner.c"
yy158:
	yyaccept = 8;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy199;
	default:	goto yy159;
	}
yy159:
#line 34 "scanner.re"
	{ return TOKEN_ELEVEN; }
#line 1076 "scanner.c"
yy160:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy200;
	default:	goto yy25;
	}
yy161:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy202;
	default:	goto yy25;
	}
yy162:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy203;
	default:	goto yy25;
	}
yy163:
	++YYCURSOR;
#line 64 "scanner.re"
	{ return TOKEN_FOURTH; }
#line 1102 "scanner.c"
yy165:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy204;
	default:	goto yy25;
	}
yy166:
	++YYCURSOR;
#line 48 "scanner.re"
	{ return TOKEN_FORTY; }
#line 1114 "scanner.c"
yy168:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy205;
	default:	goto yy25;
	}
yy169:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy207;
	default:	goto yy25;
	}
yy170:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy209;
	default:	goto yy25;
	}
yy171:
	++YYCURSOR;
#line 69 "scanner.re"
	{ return TOKEN_NINTH; }
#line 1140 "scanner.c"
yy173:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy210;
	default:	goto yy25;
	}
yy174:
	++YYCURSOR;
#line 53 "scanner.re"
	{ return TOKEN_NINETY; }
#line 1152 "scanner.c"
yy176:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy211;
	default:	goto yy25;
	}
yy177:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy213;
	default:	goto yy25;
	}
yy178:
	++YYCURSOR;
#line 62 "scanner.re"
	{ return TOKEN_SECOND; }
#line 1171 "scanner.c"
yy180:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy215;
	case 'H':
	case 'h':	goto yy216;
	case 'I':
	case 'i':	goto yy218;
	case 'Y':
	case 'y':	goto yy219;
	default:	goto yy25;
	}
yy181:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy221;
	default:	goto yy25;
	}
yy182:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy223;
	default:	goto yy25;
	}
yy183:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy224;
	default:	goto yy25;
	}
yy184:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy225;
	default:	goto yy25;
	}
yy185:
	++YYCURSOR;
#line 46 "scanner.re"
	{ return TOKEN_THIRTY; }
#line 1217 "scanner.c"
yy187:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy226;
	default:	goto yy25;
	}
yy188:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy227;
	default:	goto yy25;
	}
yy189:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy228;
	default:	goto yy25;
	}
yy190:
	++YYCURSOR;
#line 35 "scanner.re"
	{ return TOKEN_TWELVE; }
#line 1243 "scanner.c"
yy192:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy230;
	default:	goto yy25;
	}
yy193:
	++YYCURSOR;
#line 45 "scanner.re"
	{ return TOKEN_TWENTY; }
#line 1255 "scanner.c"
yy195:
	yyaccept = 9;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy231;
	default:	goto yy196;
	}
yy196:
#line 58 "scanner.re"
	{ return TOKEN_BILLION; }
#line 1267 "scanner.c"
yy197:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy232;
	default:	goto yy25;
	}
yy198:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy234;
	default:	goto yy25;
	}
yy199:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy235;
	default:	goto yy25;
	}
yy200:
	yyaccept = 10;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy237;
	default:	goto yy201;
	}
yy201:
#line 38 "scanner.re"
	{ return TOKEN_FIFTEEN; }
#line 1300 "scanner.c"
yy202:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy238;
	default:	goto yy25;
	}
yy203:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy240;
	default:	goto yy25;
	}
yy204:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy242;
	default:	goto yy25;
	}
yy205:
	yyaccept = 11;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy243;
	default:	goto yy206;
	}
yy206:
#line 55 "scanner.re"
	{ return TOKEN_HUNDRED; }
#line 1333 "scanner.c"
yy207:
	yyaccept = 12;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy244;
	default:	goto yy208;
	}
yy208:
#line 57 "scanner.re"
	{ return TOKEN_MILLION; }
#line 1345 "scanner.c"
yy209:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy245;
	default:	goto yy25;
	}
yy210:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy247;
	default:	goto yy25;
	}
yy211:
	++YYCURSOR;
#line 43 "scanner.re"
	{ return TOKEN_NINETEEN; }
#line 1364 "scanner.c"
yy213:
	++YYCURSOR;
#line 98 "scanner.re"
	{ return TOKEN_QUARTER; }
#line 1369 "scanner.c"
yy215:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy248;
	default:	goto yy25;
	}
yy216:
	++YYCURSOR;
#line 67 "scanner.re"
	{ return TOKEN_SEVENTH; }
#line 1381 "scanner.c"
yy218:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy249;
	default:	goto yy25;
	}
yy219:
	++YYCURSOR;
#line 51 "scanner.re"
	{ return TOKEN_SEVENTY; }
#line 1393 "scanner.c"
yy221:
	yyaccept = 13;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy250;
	default:	goto yy222;
	}
yy222:
#line 39 "scanner.re"
	{ return TOKEN_SIXTEEN; }
#line 1405 "scanner.c"
yy223:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy251;
	default:	goto yy25;
	}
yy224:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy253;
	default:	goto yy25;
	}
yy225:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy255;
	default:	goto yy25;
	}
yy226:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy256;
	default:	goto yy25;
	}
yy227:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy258;
	default:	goto yy25;
	}
yy228:
	++YYCURSOR;
#line 74 "scanner.re"
	{ return TOKEN_TWELFTH; }
#line 1445 "scanner.c"
yy230:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy260;
	default:	goto yy25;
	}
yy231:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy261;
	default:	goto yy25;
	}
yy232:
	yyaccept = 14;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy263;
	default:	goto yy233;
	}
yy233:
#line 41 "scanner.re"
	{ return TOKEN_EIGHTEEN; }
#line 1471 "scanner.c"
yy234:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy264;
	default:	goto yy25;
	}
yy235:
	++YYCURSOR;
#line 73 "scanner.re"
	{ return TOKEN_ELEVENTH; }
#line 1483 "scanner.c"
yy237:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy266;
	default:	goto yy25;
	}
yy238:
	++YYCURSOR;
#line 86 "scanner.re"
	{ return TOKEN_FIFTIETH; }
#line 1495 "scanner.c"
yy240:
	yyaccept = 15;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy268;
	default:	goto yy241;
	}
yy241:
#line 37 "scanner.re"
	{ return TOKEN_FOURTEEN; }
#line 1507 "scanner.c"
yy242:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy269;
	default:	goto yy25;
	}
yy243:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy271;
	default:	goto yy25;
	}
yy244:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy273;
	default:	goto yy25;
	}
yy245:
	yyaccept = 16;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy275;
	default:	goto yy246;
	}
yy246:
#line 42 "scanner.re"
	{ return TOKEN_NINETEEN; }
#line 1540 "scanner.c"
yy247:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy276;
	default:	goto yy25;
	}
yy248:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy278;
	default:	goto yy25;
	}
yy249:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy280;
	default:	goto yy25;
	}
yy250:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy281;
	default:	goto yy25;
	}
yy251:
	++YYCURSOR;
#line 87 "scanner.re"
	{ return TOKEN_SIXTIETH; }
#line 1573 "scanner.c"
yy253:
	yyaccept = 17;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy283;
	default:	goto yy254;
	}
yy254:
#line 36 "scanner.re"
	{ return TOKEN_THIRTEEN; }
#line 1585 "scanner.c"
yy255:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy284;
	default:	goto yy25;
	}
yy256:
	yyaccept = 18;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy286;
	default:	goto yy257;
	}
yy257:
#line 56 "scanner.re"
	{ return TOKEN_THOUSAND; }
#line 1604 "scanner.c"
yy258:
	yyaccept = 19;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy287;
	default:	goto yy259;
	}
yy259:
#line 59 "scanner.re"
	{ return TOKEN_TRILLION; }
#line 1616 "scanner.c"
yy260:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy288;
	default:	goto yy25;
	}
yy261:
	++YYCURSOR;
#line 95 "scanner.re"
	{ return TOKEN_BILLIONTH; }
#line 1628 "scanner.c"
yy263:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy290;
	default:	goto yy25;
	}
yy264:
	++YYCURSOR;
#line 89 "scanner.re"
	{ return TOKEN_EIGHTIETH; }
#line 1640 "scanner.c"
yy266:
	++YYCURSOR;
#line 77 "scanner.re"
	{ return TOKEN_FIFTEENTH; }
#line 1645 "scanner.c"
yy268:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy292;
	default:	goto yy25;
	}
yy269:
	++YYCURSOR;
#line 85 "scanner.re"
	{ return TOKEN_FOURTIETH; }
#line 1657 "scanner.c"
yy271:
	++YYCURSOR;
#line 92 "scanner.re"
	{ return TOKEN_HUNDREDTH; }
#line 1662 "scanner.c"
yy273:
	++YYCURSOR;
#line 94 "scanner.re"
	{ return TOKEN_MILLIONTH; }
#line 1667 "scanner.c"
yy275:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy294;
	default:	goto yy25;
	}
yy276:
	++YYCURSOR;
#line 90 "scanner.re"
	{ return TOKEN_NINETIETH; }
#line 1679 "scanner.c"
yy278:
	yyaccept = 20;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':
	case 't':	goto yy296;
	default:	goto yy279;
	}
yy279:
#line 40 "scanner.re"
	{ return TOKEN_SEVENTEEN; }
#line 1691 "scanner.c"
yy280:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy297;
	default:	goto yy25;
	}
yy281:
	++YYCURSOR;
#line 78 "scanner.re"
	{ return TOKEN_SIXTEENTH; }
#line 1703 "scanner.c"
yy283:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy299;
	default:	goto yy25;
	}
yy284:
	++YYCURSOR;
#line 84 "scanner.re"
	{ return TOKEN_THIRTIETH; }
#line 1715 "scanner.c"
yy286:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy301;
	default:	goto yy25;
	}
yy287:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy303;
	default:	goto yy25;
	}
yy288:
	++YYCURSOR;
#line 83 "scanner.re"
	{ return TOKEN_TWENTIETH; }
#line 1734 "scanner.c"
yy290:
	++YYCURSOR;
#line 80 "scanner.re"
	{ return TOKEN_EIGHTEENTH; }
#line 1739 "scanner.c"
yy292:
	++YYCURSOR;
#line 76 "scanner.re"
	{ return TOKEN_FOURTEENTH; }
#line 1744 "scanner.c"
yy294:
	++YYCURSOR;
#line 81 "scanner.re"
	{ return TOKEN_NINETEENTH; }
#line 1749 "scanner.c"
yy296:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy305;
	default:	goto yy25;
	}
yy297:
	++YYCURSOR;
#line 88 "scanner.re"
	{ return TOKEN_SEVENTIETH; }
#line 1761 "scanner.c"
yy299:
	++YYCURSOR;
#line 75 "scanner.re"
	{ return TOKEN_THIRTEENTH; }
#line 1766 "scanner.c"
yy301:
	++YYCURSOR;
#line 93 "scanner.re"
	{ return TOKEN_THOUSANDTH; }
#line 1771 "scanner.c"
yy303:
	++YYCURSOR;
#line 96 "scanner.re"
	{ return TOKEN_TRILLIONTH; }
#line 1776 "scanner.c"
yy305:
	++YYCURSOR;
#line 79 "scanner.re"
	{ return TOKEN_SEVENTEENTH; }
#line 1781 "scanner.c"
}
#line 147 "scanner.re"

}

/*
scanstate* numerizer_attach(scanstate *ss)
{
	if(ss) {
		ss->state = numerizer_start;
		ss->line = 1;
	}

	return ss;
}
*/
